print('enter a number A:')
A=input()
print('type of A is',type(A))
print(A)
print('enter a number B:')
B=int(input())
print('type of B is',type(B))
print(B)
C=bool(input())
print('type of C is',type(C))
print(C)
D=float(input())
